export type Lang = "en" | "ar";

export const landingCopy = {
  en: {
    navFeatures: "Features",
    navBlog: "Blog",
    navFaq: "FAQ",
    navCta: "Login",
    navSignin: "Sign in",
    heroLabel: "GYM MANAGEMENT · REDEFINED",
    heroTitle: "Run your gym without the",
    heroTitleEm: "admin headache.",
    heroSub: "GymFlow automates memberships, check-ins, renewals, and reports — so you can focus on what matters: your clients.",
    heroCta: "Free Trial",
    heroCtaSecondary: "Get pricing",
    heroMicro: "Arabic + English · Built for gyms in Egypt and the Gulf",
    problemLabel: "THE PROBLEM",
    problemTitle: "Running a gym shouldn't feel like a second full-time job.",
    problemCards: [
      { title: "Missed renewals bleed revenue", body: "Clients lapse without reminders. You only notice when they're already gone — and so is their subscription fee." },
      { title: "Manual check-ins create queues", body: "Hand-written logs and manual ID searches make your front desk a bottleneck every single morning." },
      { title: "You're flying blind", body: "Spreadsheets don't show which plans are growing, which clients are at risk, or where your revenue is coming from." },
    ] as const,
    howLabel: "HOW IT WORKS",
    howTitle: "From setup to running — in one afternoon.",
    howSteps: [
      { num: "01", title: "Import or add your clients", body: "Upload your existing client list or start fresh. GymFlow migrates your data quickly and securely." },
      { num: "02", title: "Configure plans & automations", body: "Set your membership tiers, pricing, session quotas, and renewal reminders. Done once, runs forever." },
      { num: "03", title: "Manage from one dashboard", body: "Check-ins, reports, renewals, and messages — all in one place. No more switching between tools." },
    ] as const,
    featuresLabel: "FEATURES",
    featuresTitle: "Everything your gym needs. Nothing it doesn't.",
    featuresCards: [
      { title: "Smart Check-ins", body: "QR code scanning with automatic access control. Expired members are denied instantly. Works offline — scans queue and sync when you're back online.", size: "large" as const, badge: "Most used feature" },
      { title: "WhatsApp Automation", body: "Renewal reminders, payment recovery sequences, welcome messages, and broadcasts — all sent automatically via WhatsApp. Recover up to 30% of lapsed members.", size: "large" as const, badge: "Revenue saver" },
      { title: "Revenue & Risk Reports", body: "See revenue at risk from expiring members, ghost members who pay but don't show up, and month-over-month income trends — in real EGP numbers.", size: "small" as const },
      { title: "PT & Staff Management", body: "Trainer profiles, session tracking, package management, and staff roles — all from one hub.", size: "small" as const },
      { title: "Income Tracking", body: "Monthly revenue breakdown with MoM deltas, PT revenue split, expected monthly income, and per-day earnings calendar.", size: "medium" as const },
      { title: "Works Offline", body: "Full offline mode for the front desk. Check-ins, member lookups, and actions queue locally and sync automatically when internet returns.", size: "medium" as const },
    ] as const,
    faqLabel: "FAQ",
    faqTitle: "Questions answered.",
    faqItems: [
      { q: "How do I migrate my existing client data?", a: "You can import clients via CSV upload or use our migration tool to bring data from your current system. Our support team assists with any complex transfers." },
      { q: "Does GymFlow work for multi-branch gyms?", a: "Yes. GymFlow supports both single-branch and multi-branch operations. We scope setup, reporting, and rollout around your branch structure." },
      { q: "What happens when a client's subscription expires?", a: "Expired clients are automatically denied entry at check-in. You can configure automated WhatsApp renewal reminders to go out 7, 3, and 1 day before expiry." },
      { q: "Is my clients' data secure?", a: "All data is encrypted in transit and at rest. We use Google Cloud infrastructure with daily backups and ISO-standard security practices." },
      { q: "How does pricing work?", a: "GymFlow uses a quote-first business model. Pricing depends on your gym size, branch setup, rollout needs, and support scope, and the final terms are confirmed in writing before launch." },
    ] as const,
    ctaTitle: "Ready to get your time back?",
    ctaSub: "Join gym owners across the region who run their operations with GymFlow.",
    ctaBtn: "Start Free Trial",
    ctaSecondary: "Book a Demo",
    ctaMicro: "Start on your own today · Get guided setup for bigger rollouts",
    previewLabel: "SEE IT IN ACTION",
    previewTitle: "A real look at the dashboard.",
    previewTabs: [
      { key: "home", label: "Dashboard", src: "/demo-screens/dashboard.png" },
      { key: "members", label: "Members", src: "/demo-screens/members.png" },
      { key: "reports", label: "Reports", src: "/demo-screens/reports.png" },
      { key: "income", label: "Income", src: "/demo-screens/income.png" },
      { key: "subscriptions", label: "Subscriptions", src: "/demo-screens/subscriptions.png" },
      { key: "pt", label: "PT & Staff", src: "/demo-screens/pt.png" },
    ] as const,
    footerTagline: "Gym management, simplified.",
    footerLegalCenter: "Legal Center",
    footerPrivacy: "Privacy Policy",
    footerTerms: "Terms of Service",
    footerBilling: "Billing & Refunds",
    footerCookies: "Cookie Notice",
    footerSecurity: "Security",
    footerContact: "Contact",
    footerCopyright: "© 2026 GymFlow. All rights reserved.",
    footerProduct: "Product",
    footerAllFeatures: "All Features",
    footerQrCheckin: "QR Check-in",
    footerWhatsapp: "WhatsApp Notifications",
    footerSubscriptions: "Subscription Management",
    footerResources: "Resources",
    footerBlog: "Blog",
    footerSolutions: "Solutions",
    footerCompare: "Compare",
    footerLocations: "Locations",
    footerLocationCairo: "Cairo",
    footerLocationRiyadh: "Riyadh",
    footerLocationDubai: "Dubai",
    footerLocationJeddah: "Jeddah",
    footerLocationAlex: "Alexandria",
  },
  ar: {
    navFeatures: "المزايا",
    navBlog: "المدونة",
    navFaq: "الأسئلة الشائعة",
    navCta: "تسجيل الدخول",
    navSignin: "تسجيل الدخول",
    heroLabel: "إدارة الصالات الرياضية · بأسلوب أذكى",
    heroTitle: "أدِر صالتك الرياضية بلا",
    heroTitleEm: "عناء الإدارة.",
    heroSub: "يتولى GymFlow الاشتراكاتِ وتسجيلَ الدخول والتجديداتِ تلقائياً — لتتفرّغ لما يهمّ حقاً: عملاؤك.",
    heroCta: "تجربة مجانية",
    heroCtaSecondary: "اطلب السعر",
    heroMicro: "عربي + English · مصمم للجيمات في مصر والخليج",
    problemLabel: "المشكلة",
    problemTitle: "إدارة الصالة الرياضية لا ينبغي أن تستنزف كل وقتك.",
    problemCards: [
      { title: "الاشتراكات المنتهية تُنزف إيراداتك", body: "تنتهي اشتراكات العملاء دون أي تنبيه، ولا تدرك ذلك إلا بعد فوات الأوان — ومعهم رسومهم." },
      { title: "تسجيل الدخول اليدوي يُعطّل سير العمل", body: "السجلات الورقية والبحث اليدوي يحوّلان مكتب الاستقبال إلى نقطة اختناق في كل صباح." },
      { title: "تعمل دون بيانات واضحة", body: "جداول البيانات لا تُخبرك أيّ الخطط تنمو، ولا مَن من عملائك في خطر، ولا مصادر إيراداتك." },
    ] as const,
    howLabel: "آلية العمل",
    howTitle: "من الإعداد إلى التشغيل — في يوم واحد.",
    howSteps: [
      { num: "01", title: "أضف عملاءك أو استوردهم", body: "حمّل قائمة عملائك الحالية أو ابدأ من الصفر. ينقل GymFlow بياناتك بسرعة وأمان." },
      { num: "02", title: "اضبط الخطط والتجديدات التلقائية", body: "حدّد مستويات العضوية والأسعار وحصص الجلسات وتذكيرات التجديد. تُضبط مرة واحدة وتعمل تلقائياً." },
      { num: "03", title: "أدِر كل شيء من لوحة واحدة", body: "تسجيل الدخول والتقارير والتجديدات والرسائل — جميعها في مكان واحد، دون التنقل بين أدوات متعددة." },
    ] as const,
    featuresLabel: "المزايا",
    featuresTitle: "كل ما تحتاجه صالتك الرياضية. لا أقل ولا أكثر.",
    featuresCards: [
      { title: "تسجيل دخول ذكي", body: "مسح رمز QR مع التحكم التلقائي في الدخول. يُرفض الأعضاء المنتهية اشتراكاتهم فوراً. يعمل بدون إنترنت — تُخزّن عمليات المسح وتُزامَن عند العودة.", size: "large" as const, badge: "الأكثر استخداماً" },
      { title: "أتمتة واتساب", body: "تذكيرات التجديد وتسلسلات استرداد المدفوعات ورسائل الترحيب والبث — تُرسل جميعها تلقائياً عبر واتساب. استرداد حتى 30% من الأعضاء المنقطعين.", size: "large" as const, badge: "موفّر الإيرادات" },
      { title: "تقارير الإيرادات والمخاطر", body: "اعرف الإيرادات المعرّضة للخطر من الاشتراكات المنتهية، والأعضاء الوهميين الذين يدفعون دون حضور، واتجاهات الدخل الشهرية — بالأرقام الفعلية.", size: "small" as const },
      { title: "إدارة المدربين والفريق", body: "ملفات المدربين وتتبع الجلسات وإدارة الباقات وأدوار الموظفين — الكل من مكان واحد.", size: "small" as const },
      { title: "تتبع الإيرادات", body: "تفصيل الإيرادات الشهرية مع مقارنات شهرية، وتقسيم إيرادات التدريب الشخصي، والدخل الشهري المتوقع، وتقويم الأرباح اليومية.", size: "medium" as const },
      { title: "يعمل بدون إنترنت", body: "وضع كامل للعمل بدون إنترنت لمكتب الاستقبال. تسجيل الدخول والبحث عن الأعضاء والإجراءات تُخزّن محلياً وتُزامَن تلقائياً عند عودة الإنترنت.", size: "medium" as const },
    ] as const,
    faqLabel: "الأسئلة الشائعة",
    faqTitle: "أسئلة يطرحها الجميع",
    faqItems: [
      { q: "كيف أنقل بيانات عملائي الحاليين؟", a: "يمكنك استيراد العملاء عبر رفع ملف CSV أو استخدام أداة الترحيل لنقل البيانات من نظامك الحالي. يساعدك فريق الدعم في أي عملية نقل معقدة." },
      { q: "هل يعمل GymFlow مع الصالات متعددة الفروع؟", a: "نعم. يدعم GymFlow الجيمات ذات الفرع الواحد أو الفروع المتعددة، ويتم تحديد الإعداد والتقارير وآلية الإطلاق بحسب هيكل فروعك." },
      { q: "ماذا يحدث عند انتهاء اشتراك العميل؟", a: "يُرفض دخول العملاء المنتهية اشتراكاتهم تلقائياً. يمكنك ضبط تذكيرات تجديد تلقائية عبر واتساب قبل 7 و3 و1 أيام من انتهاء الاشتراك." },
      { q: "هل بيانات عملائي آمنة؟", a: "جميع البيانات مشفّرة أثناء النقل وعند التخزين. نعتمد على البنية التحتية لـ Google Cloud مع نسخ احتياطية يومية وممارسات أمان وفق معايير دولية." },
      { q: "كيف تعمل الأسعار؟", a: "يعتمد GymFlow على نموذج تجاري يبدأ بعرض سعر. ويتم تحديد السعر بحسب حجم الجيم وعدد الفروع واحتياجات الإطلاق والدعم، ثم تُؤكد الشروط كتابةً قبل البدء." },
    ] as const,
    ctaTitle: "هل أنت مستعد لاستعادة وقتك؟",
    ctaSub: "انضم إلى صالات رياضية في المنطقة تدير أعمالها باحترافية مع GymFlow.",
    ctaBtn: "ابدأ تجربتك المجانية",
    ctaSecondary: "احجز عرضًا توضيحيًا",
    ctaMicro: "ابدأ بنفسك اليوم · واحصل على مساعدة موجهة إذا كان الإطلاق أكبر",
    previewLabel: "شاهده بنفسك",
    previewTitle: "نظرة حقيقية على لوحة التحكم.",
    previewTabs: [
      { key: "home", label: "لوحة التحكم", src: "/demo-screens/dashboard.png" },
      { key: "members", label: "الأعضاء", src: "/demo-screens/members.png" },
      { key: "reports", label: "التقارير", src: "/demo-screens/reports.png" },
      { key: "income", label: "الإيرادات", src: "/demo-screens/income.png" },
      { key: "subscriptions", label: "الاشتراكات", src: "/demo-screens/subscriptions.png" },
      { key: "pt", label: "التدريب والفريق", src: "/demo-screens/pt.png" },
    ] as const,
    footerTagline: "إدارة الجيم، مُبسَّطة.",
    footerLegalCenter: "المركز القانوني",
    footerPrivacy: "سياسة الخصوصية",
    footerTerms: "شروط الخدمة",
    footerBilling: "الفوترة والاسترداد",
    footerCookies: "إشعار الكوكيز",
    footerSecurity: "الأمان",
    footerContact: "التواصل",
    footerCopyright: "© 2026 GymFlow. جميع الحقوق محفوظة.",
    footerProduct: "المنتج",
    footerAllFeatures: "جميع المزايا",
    footerQrCheckin: "تسجيل دخول QR",
    footerWhatsapp: "إشعارات واتساب",
    footerSubscriptions: "إدارة الاشتراكات",
    footerResources: "الموارد",
    footerBlog: "المدونة",
    footerSolutions: "الحلول",
    footerCompare: "المقارنات",
    footerLocations: "المواقع",
    footerLocationCairo: "القاهرة",
    footerLocationRiyadh: "الرياض",
    footerLocationDubai: "دبي",
    footerLocationJeddah: "جدة",
    footerLocationAlex: "الإسكندرية",
  },
} as const;
